#!/usr/bin/python

# This file generated by a program. do not edit.
import EUtils.POM

#     
# This is the Current DTD for Entrez eSummary version 2
# $Id: eSummary_041029.dtd 49514 2004-10-29 15:52:04Z parantha $
# 
#  ================================================================= 
class Id(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel(('', [('#PCDATA', '')], ''))


#  \d+ 
class Item(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel(('|', [('#PCDATA', ''), (u'Item', '')], '*'))
	ATTLIST = EUtils.POM.AttributeList([EUtils.POM.XMLAttribute('Name', 1, 11, None), EUtils.POM.XMLAttribute('Type', ['Integer', 'Date', 'String', 'Structure', 'List', 'Flags', 'Qualifier', 'Enumerator', 'Unknown'], 11, None)])


#  .+ 
class ERROR(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel(('', [('#PCDATA', '')], ''))


#  .+ 
class DocSum(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel((u',', [(u'Id', ''), (u'Item', u'+')], ''))


class eSummaryResult(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel((u'|', [(u'DocSum', ''), (u'ERROR', '')], u'+'))

