#!/usr/bin/python

# This file generated by a program. do not edit.
import EUtils.POM

#     
#                 This is the Current DTD for Entrez eSummary
# $Id: eSummary_020511.dtd,v 1.5 2002/11/06 16:11:49 olegh Exp $
# 
#  ================================================================= 
class Id(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel(('', [('#PCDATA', '')], ''))


#  \d+ 
class Item(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel(('|', [('#PCDATA', ''), (u'Item', '')], '*'))
	ATTLIST = EUtils.POM.AttributeList([EUtils.POM.XMLAttribute('Name', 1, 11, None), EUtils.POM.XMLAttribute('Type', ['Integer', 'Date', 'String', 'List', 'Unknown'], 11, None)])


#  .+ 
class ERROR(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel(('', [('#PCDATA', '')], ''))


#  .+ 
class DocSum(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel((u',', [(u'Id', ''), (u'Item', u'+')], ''))


class eSummaryResult(EUtils.POM.ElementNode):
	CONTENTMODEL = EUtils.POM.ContentModel((u'|', [(u'DocSum', u'*'), (u'ERROR', u'?')], ''))

